notifications:
  email:
    on_success: never
    on_failure: change

language: node_js
node_js:
  - '10'

os: windows

branches:
  only:
    - master
    - /releases\/.+/

install:
  - npm install

script:
  - npm run lint && npm run build
